import sqlite3
from datetime import datetime
from alert_engine import DB_FILE

REPORT_FILE = "registry_report.txt"


def fetch_change_log() -> list:
    """Fetch all changes from SQLite database."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM change_log ORDER BY timestamp ASC")
    rows = cursor.fetchall()
    conn.close()
    return rows


def fetch_scan_summaries() -> list:
    """Fetch all scan summaries from database."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM scan_summary ORDER BY scan_time ASC")
    rows = cursor.fetchall()
    conn.close()
    return rows


def fetch_severity_counts() -> dict:
    """Count changes by severity level."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT severity, COUNT(*) FROM change_log GROUP BY severity
    """)
    rows = cursor.fetchall()
    conn.close()
    return {row[0]: row[1] for row in rows}


def fetch_critical_changes() -> list:
    """Fetch only critical changes for executive summary."""
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT timestamp, key_path, value_name, old_value, new_value, alert_message
        FROM change_log
        WHERE severity = 'CRITICAL'
        ORDER BY timestamp ASC
    """)
    rows = cursor.fetchall()
    conn.close()
    return rows


def generate_report() -> None:
    """Generate full registry change report as text file."""

    changes = fetch_change_log()
    summaries = fetch_scan_summaries()
    severity_counts = fetch_severity_counts()
    critical_changes = fetch_critical_changes()

    total_changes = len(changes)
    critical = severity_counts.get("CRITICAL", 0)
    warning = severity_counts.get("WARNING", 0)
    info = severity_counts.get("INFO", 0)

    lines = []

    # Header
    lines.append("=" * 65)
    lines.append("       WINDOWS REGISTRY CHANGE MONITORING REPORT")
    lines.append("       Generated by: SentinelShield Registry Monitor")
    lines.append(f"       Report Date : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("=" * 65)

    # Executive Summary
    lines.append("\n[ EXECUTIVE SUMMARY ]")
    lines.append("-" * 65)
    lines.append(f"  Total Scans Completed : {len(summaries)}")
    lines.append(f"  Total Changes Detected: {total_changes}")
    lines.append(f"  Critical Alerts       : {critical}")
    lines.append(f"  Warnings              : {warning}")
    lines.append(f"  Informational         : {info}")

    if critical > 0:
        lines.append("\n  [!!!] SYSTEM STATUS: COMPROMISED")
        lines.append("        Immediate investigation recommended.")
    elif warning > 0:
        lines.append("\n  [ ! ] SYSTEM STATUS: SUSPICIOUS ACTIVITY DETECTED")
        lines.append("        Review flagged entries.")
    else:
        lines.append("\n  [ + ] SYSTEM STATUS: CLEAN")

    # Scan History
    lines.append("\n\n[ SCAN HISTORY ]")
    lines.append("-" * 65)
    for i, summary in enumerate(summaries, 1):
        _, scan_time, total, crit, warn, inf = summary
        lines.append(f"  Scan #{i} | {scan_time}")
        lines.append(f"           Changes: {total} | "
                     f"Critical: {crit} | Warning: {warn} | Info: {inf}")

    # Critical Changes Detail
    if critical_changes:
        lines.append("\n\n[ CRITICAL ALERTS — DETAILED ]")
        lines.append("-" * 65)
        for i, change in enumerate(critical_changes, 1):
            timestamp, key_path, value_name, old_val, new_val, alert_msg = change
            lines.append(f"\n  Alert #{i}")
            lines.append(f"  Time      : {timestamp}")
            lines.append(f"  Key Path  : {key_path}")
            lines.append(f"  Value     : {value_name}")
            lines.append(f"  Old Value : {old_val}")
            lines.append(f"  New Value : {new_val}")
            lines.append(f"  Alert     : {alert_msg}")

    # Full Change Log
    lines.append("\n\n[ FULL CHANGE LOG ]")
    lines.append("-" * 65)

    if not changes:
        lines.append("  No changes recorded.")
    else:
        for row in changes:
            (id_, timestamp, change_type, key_path,
             value_name, old_val, new_val, severity, alert_msg) = row
            lines.append(f"\n  ID        : {id_}")
            lines.append(f"  Severity  : {severity}")
            lines.append(f"  Timestamp : {timestamp}")
            lines.append(f"  Type      : {change_type}")
            lines.append(f"  Key Path  : {key_path}")
            lines.append(f"  Value     : {value_name}")
            lines.append(f"  Old Value : {old_val}")
            lines.append(f"  New Value : {new_val}")
            lines.append(f"  Alert     : {alert_msg}")
            lines.append("  " + "-" * 40)

    # Footer
    lines.append("\n" + "=" * 65)
    lines.append("  END OF REPORT")
    lines.append("  SentinelShield Registry Monitor — Simulation Mode")
    lines.append("=" * 65)

    # Write to file
    with open(REPORT_FILE, "w") as f:
        f.write("\n".join(lines))

    # Print to screen
    print("\n".join(lines))
    print(f"\n[+] Report saved to: {REPORT_FILE}")


if __name__ == "__main__":
    generate_report()
